preload = ['./.config/plugins/index.ts']
jsx = "react-jsx"
jsxImportSource = "react"

[define]
"Bun.origin" = "'http://127.0.0.1:3000/'"
"import.meta.env.SSR" = "true"

[loader]
".css" = "css"
".tsx" = "tsx"
".ts" ="ts"