preload = ['./.config/plugins/index.ts']
jsx = "react-jsx"
jsxImportSource = "react"
publicDir = "./public"

[define]
"Bun.origin" = "'http://0.0.0.0:8080'"
"import.meta.env.SSR" = "true"

[loader]
".css" = "file"
".tsx" = "tsx"
".ts" ="ts"